sources_debian_json:
    pattern:  /json/{mot}/{relations}/{limite}
    defaults: { _controller: SourcesDebianBundle:Default:json }

sources_debian_bidon:
    pattern:  /bidon/{mot}/{relations}/{limite}
    defaults: { _controller: SourcesDebianBundle:Default:jsonbidon }

sources_debian_relations:
    pattern:  /relations
    defaults: { _controller: SourcesDebianBundle:Default:jsonrelations }
