parameters:
#    sources_debian.example.class: Sources\DebianBundle\Example

services:
#    sources_debian.example:
#        class: %sources_debian.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
