vues_representations_json:
    pattern:  /json/{data}
    defaults: { _controller: VuesRepresentationsBundle:Default:json }

vues_representations_jsongraph:
    pattern:  /jsonGraph/{data}
    defaults: { _controller: VuesRepresentationsBundle:Default:jsonGraph }
