vues_representations_json:
    pattern:  /json
    defaults: { _controller: VuesRepresentationsBundle:Default:json }

vues_representations_jsongraph:
    pattern:  /jsonGraph
    defaults: { _controller: VuesRepresentationsBundle:Default:jsonGraph }

vues_representations_bubble:
    pattern:  /bubble
    defaults: { _controller: VuesRepresentationsBundle:Default:bubble }

vues_representations_indented:
    pattern:  /indented
    defaults: { _controller: VuesRepresentationsBundle:Default:indented }

vues_representations_force:
    pattern:  /force
    defaults: { _controller: VuesRepresentationsBundle:Default:force }

vues_representations_radial:
    pattern:  /radial
    defaults: { _controller: VuesRepresentationsBundle:Default:radial }
