parameters:
#    sources_getty.example.class: Sources\GettyBundle\Example

services:
#    sources_getty.example:
#        class: %sources_getty.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
