sources_db_pedia_json:
    pattern:  /json/{mot}/{relations}/{limite}
    defaults: { _controller: SourcesDbPediaBundle:Default:json }

sources_db_pedia_bidon:
    pattern:  /bidon/{mot}/{relations}/{limite}
    defaults: { _controller: SourcesDbPediaBundle:Default:jsonbidon }

sources_db_pedia_relations:
    pattern:  /relations
    defaults: { _controller: SourcesDbPediaBundle:Default:jsonrelations }

sources_db_pedia_fenetre:
    pattern:  /fenetre/{mot}
    defaults: { _controller: SourcesDbPediaBundle:Default:fenetre, mot:Horse }
