security:
    encoders:
        JC\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: true

        main:
            pattern:  ^/
            anonymous: true
            provider:  main
            form_login:
                provider:               main
                login_path:             fos_user_security_login 
                check_path:             fos_user_security_check
                csrf_provider:          form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
