<?php
/**
	* Modèle : l'objet Recherche représente l'ensemble des paramètres de recherche utilisés à un moment donné par un utilisateur donné
	*
	* This class was generated by the Doctrine ORM. Add your own custom
	* repository methods below.
	*
	* @author Juliana Leclaire <Juliana.Leclaire@etu.univ-savoie.fr>
	* @author Céline de Roland <Celine.de-Roland@etu.univ-savoie.fr>
	*
	* @version = 2.0
	*/
namespace Relais\RelaisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
	* Modèle : l'objet Recherche représente l'ensemble des paramètres de recherche utilisés à un moment donné par un utilisateur donné
	*
	* This class was generated by the Doctrine ORM. Add your own custom
	* repository methods below.
	*
	* @author Juliana Leclaire <Juliana.Leclaire@etu.univ-savoie.fr>
	* @author Céline de Roland <Celine.de-Roland@etu.univ-savoie.fr>
	*
	* @version = 2.0
	*/
class RechercheRepository extends EntityRepository
{

/**
	* @param $user
	* @param $prio : liste de choses
	*/
	public function trier($user, $prio, $impose)
	{
		$prio = explode(',',$prio);
		foreach($prio as $valeur)
		{
			$binome = explode('-',$valeur);
			$tabprio[$binome[0]] = $binome[1];
		}
		$tabimpose = array('user' => $user);
		if ($impose != 'none')
		{
			$impose = explode(',',$impose);
			foreach($impose as $valeur)
			{
				$binome = explode('-',$valeur);
				$tabimpose[$binome[0]] = $binome[1];
			}
		}
		return $this -> findBy($tabimpose, $tabprio);
	}
}
