jc_front_homepage:
    pattern:  /{_locale}
    defaults: { _controller: JCFrontBundle:Default:index, _locale:en }

jc_front_tests:
    pattern:  /admin/{_locale}/tests
    defaults: {_controller: JCFrontBundle:Default:test, _locale:en }
