parameters:
#    jc_front.example.class: JC\FrontBundle\Example

services:
#    jc_front.example:
#        class: %jc_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
