relais_relais_homepage:
    pattern:  /
    defaults: {_controller: RelaisRelaisBundle:Default:index, _locale:en }

relais_relais_layout:
    pattern:  /layout
    defaults: { _controller: RelaisRelaisBundle:Default:layout }

relais_relais_layoutRelations:
    pattern:  /layoutrelations
    defaults: { _controller: RelaisRelaisBundle:Default:layoutrelations }

relais_relais_historique:
    pattern:  /historique
    defaults: { _controller: RelaisRelaisBundle:Default:historique }

relais_relais_show_historique:
    pattern:  /historique/show/{prio}/{impose}
    defaults: { _controller: RelaisRelaisBundle:Default:showhistorique, prio:date-desc, impose:none }

relais_relais_show_historique_min:
    pattern:  /historique/min/show/{prio}/{impose}
    defaults: { _controller: RelaisRelaisBundle:Default:showhistoriquemin, prio:date-desc, impose:none }

relais_relais_favori_change:
    pattern:  /historique/change/{id}
    defaults: { _controller: RelaisRelaisBundle:Default:changefavorite }


