relais_relais_homepage:
    pattern:  /
    defaults: {_controller: RelaisRelaisBundle:Default:index, _locale:en }

relais_relais_layout:
    pattern:  /layout
    defaults: { _controller: RelaisRelaisBundle:Default:layout }

relais_relais_layoutRelations:
    pattern:  /layoutrelations
    defaults: { _controller: RelaisRelaisBundle:Default:layoutrelations }

relais_relais_historique:
    pattern:  /historique/{source}
    defaults: { _controller: RelaisRelaisBundle:Default:historique }

