sources_wordnet_bidon:
    pattern:  /bidon/{relations}/{limite}
    defaults: { _controller: SourcesWordNetBundle:Default:jsonbidon }

sources_wordnet_relations:
    pattern:  /relations
    defaults: { _controller: SourcesWordNetBundle:Default:jsonrelations }
